# Generated by Django 3.0.4 on 2020-06-05 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero de control')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('carrera', models.CharField(max_length=30, verbose_name='carrera')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('TotalPrestamos', models.IntegerField(verbose_name='Total de prestamos')),
                ('totalAdeudos', models.IntegerField(verbose_name='Total de adeudos')),
                ('numeroAdeudo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Articulo')),
                ('area', models.CharField(max_length=30, verbose_name='Area')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.articulos', verbose_name='Articulo')),
                ('numeroControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.alumnos', verbose_name='Numero de control')),
            ],
        ),
        migrations.CreateModel(
            name='adeudos',
            fields=[
                ('numeroAdeudo', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero de adeudo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.articulos', verbose_name='Articulo')),
                ('numeroControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.alumnos', verbose_name='Numero de control')),
            ],
        ),
    ]
