# Generated by Django 3.0.4 on 2020-06-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='numeroAdeudo',
        ),
    ]
