# Generated by Django 3.0.4 on 2020-06-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0002_remove_alumnos_numeroadeudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='area',
            field=models.CharField(choices=[('biblioteca', 'Biblioteca'), ('laboratorio de computo', 'Laboratorio de computo'), ('laboratorio de quimica', 'Laboratorio de quimica'), ('laller de electronica', 'Taller de electronica'), ('taller de industrial', 'Taller de industrial'), ('financieros', 'Financieros')], max_length=30, verbose_name='Area'),
        ),
    ]
