# Generated by Django 3.0.4 on 2020-06-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0002_auto_20200603_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.articulos', verbose_name='Articulo'),
        ),
    ]
