# Generated by Django 2.2.3 on 2020-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Usuario')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('img', models.CharField(max_length=50, verbose_name='Foto')),
            ],
        ),
    ]
