# Generated by Django 2.2.3 on 2020-05-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='area',
            field=models.CharField(default=1, max_length=50, verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
    ]
