# Generated by Django 3.0.4 on 2020-06-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200527_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='area',
            field=models.CharField(choices=[('biblioteca', 'Biblioteca'), ('laboratorio de computo', 'Laboratorio de computo'), ('laboratorio de quimica', 'Laboratorio de quimica'), ('laller de electronica', 'Taller de electronica'), ('taller de industrial', 'Taller de industrial')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('escolares', 'Control Escolar'), ('laboratorios', 'Laboratorios')], max_length=50, verbose_name='Tipo'),
        ),
    ]
